services:
  backend:
    build:
      context: ./backend
    container_name: breaktime-backend
    ports:
      - "8002:8001"

  frontend:
    build:
      context: ./frontend
    container_name: breaktime-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
